version: "3.9"
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "80:3000"

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - /usr/local/var/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
